# Generated by Django 4.0.4 on 2023-06-07 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartStudio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
