# Generated by Django 4.0.4 on 2023-06-07 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartStudio', '0002_remove_photo_album_delete_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date_taken',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
