# Generated by Django 4.0.4 on 2023-06-08 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartStudio', '0004_photo_category_alter_photo_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='category',
            new_name='Category',
        ),
    ]
